<wsdl:definitions
     name="fileReferenceWrite"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Activities/TranslateActivity/fileReferenceWrite"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Activities/TranslateActivity/fileReferenceWrite"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:imp1="ikea.com/system/xsd/iipcusis/proforma/proformaload/1.0/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Write_plt" >
    <plt:role name="Write_role" >
      <plt:portType name="tns:Write_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Activities/TranslateActivity/fileReferenceWrite"
              xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="ikea.com/system/xsd/iipcusis/proforma/proformaload/1.0/" schemaLocation="../Schemas/Load.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Write_msg">
        <wsdl:part name="body" element="imp1:SyncLoad"/>
    </wsdl:message>
    <wsdl:portType name="Write_ptt">
        <wsdl:operation name="Write">
            <wsdl:input message="tns:Write_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
